### ISSUE TITLE
no records in Mesos DNS

### ISSUE THREAD

**Issue by mikestaub** [arangodb/arangodb-dcos#2]
I just installed the latest DCOS 1.4 on a new cluster and ran: 
dcos package install arangodb.

Once everything was setup, I logged into my mesos master node and ran:
dig coordinator1.arangodb.mesos 
and then:
dig _coordinator1._tcp.arangodb.mesos

but I don't see any records for either. How can I connect to the cluster from my clients?

**Comment by neunhoef** [comment]
Sorry for the delay over the christmas holidays. I just tried the very same and seem to have the same problem, there are no records. The strange thing is that mesos-dns seems to get notified about these addresses, since I see them in the log of mesos-dns. I will investigate.

An alternative is to open the mesos console at
  `http://YOUR_MESOS_MASTER_URL/mesos`
and locate the coordinator task there. Under "Host" you see the (internal) IP address and if you click on "Sandbox" and look at the stdout stream you see an output "PORT0=...".

But this is obviously not easily automated and not the recommended way for service discovery...

**Comment by neunhoef** [comment]
Have sent a question to the dcos-community slack channel for help. Needs further attention.

**Comment by mikestaub** [comment]
Thanks for looking into this, I am hardcoding the host:port like you suggested as a workaround.

**Comment by m0ppers** [comment]
Sorry for the huge delay :( We failed to properly track and push it in the dcos community :( Sorry for that :(

Meanwhile we had a chance to have a look at it again and found the reason why this stopped working. A fix will be included in the new (pending) release. I hope it is available very soon. We are in close contact with the guys @mesosphere :)

You can track its progress here:

https://github.com/mesosphere/universe/pull/291

If you want to test it yourself you can do

```
dcos config set package.sources '["https://github.com/m0ppers/universe/archive/arangodb-2.8.zip", "https://github.com/mesosphere/universe/archive/version-1.x.zip"]'
dcos package update
dcos package install arangodb
```

**Comment by mikestaub** [comment]
Thanks, I will be creating a new DCOS community cluster next week and will give this a try.

**Comment by mikestaub** [comment]
I tested this and it indeed is fixed, thanks!

**Comment by m0ppers** [comment]
:+1:
